/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiplicacion_matrices;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Equipo01
 */
public class Ventana extends javax.swing.JFrame {

    Matriz Matriz1 = new Matriz();
    Matriz Matriz2 = new Matriz();
    
    public void GenerarMatriz(int f1,int f2,int c1,int c2){   
        
        
        }
    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        f1 = new javax.swing.JTextField();
        c1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        f2 = new javax.swing.JTextField();
        c2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnmulti = new javax.swing.JButton();
        btng = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        Matrizz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Matrizz1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        Matrizf = new javax.swing.JTable();
        lberror = new javax.swing.JLabel();
        btnsuma = new javax.swing.JButton();
        btntras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, null, new java.awt.Color(0, 0, 0), null, null));

        jLabel4.setText("#FILAS:");

        jLabel7.setText("#COLUMNAS:");

        f1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f1ActionPerformed(evt);
            }
        });

        c1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(f1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(c1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        f2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        f2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                f2ActionPerformed(evt);
            }
        });

        c2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });

        jLabel6.setText("#FILAS:");

        jLabel9.setText("#COLUMNAS:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(f2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(c2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel3.setText("MULTIPLICACION ENTRE MATRICES");

        btnmulti.setText("MULTIPLICAR");
        btnmulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmultiActionPerformed(evt);
            }
        });

        btng.setText("GENERAR");
        btng.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngMouseClicked(evt);
            }
        });

        Matrizz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Matrizz.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jScrollPane3.setViewportView(Matrizz);

        jLabel1.setText("Matriz A");

        jLabel2.setText("Matriz B");

        Matrizz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(Matrizz1);

        Matrizf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        Matrizf.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jScrollPane5.setViewportView(Matrizf);

        lberror.setFont(new java.awt.Font("Arial", 3, 10)); // NOI18N
        lberror.setForeground(new java.awt.Color(255, 0, 0));

        btnsuma.setText("SUMAR");
        btnsuma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnsumaMouseClicked(evt);
            }
        });
        btnsuma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumaActionPerformed(evt);
            }
        });

        btntras.setText("TRASPUESTA");
        btntras.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btntrasMouseMoved(evt);
            }
        });
        btntras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btntrasMouseClicked(evt);
            }
        });
        btntras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(206, 206, 206))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(199, 211, Short.MAX_VALUE)
                .addComponent(btng)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lberror, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(btnmulti)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnsuma)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btntras)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btng)
                            .addComponent(lberror, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnmulti)
                    .addComponent(btnsuma)
                    .addComponent(btntras))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(137, 137, 137))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnmultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmultiActionPerformed
        // TODO add your handling code here:
        int dato1,dato2,k,i,j,s=0;
        
        DefaultTableModel modelo1 = (DefaultTableModel) Matrizz.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) Matrizz1.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) Matrizf.getModel();
               
            modelo1.setRowCount(Matriz1.Num_filas);
            modelo1.setColumnCount(Matriz1.Num_columnas);
            modelo2.setRowCount(Matriz2.Num_filas);
            modelo2.setColumnCount(Matriz2.Num_columnas);
            
            
            if(Matriz1.Num_columnas==Matriz2.Num_filas){
                
                modelo3.setRowCount(Matriz1.Num_columnas);
                modelo3.setColumnCount(Matriz2.Num_filas);
                
                for(i=0;i<=Matriz1.Num_filas;i++){
                    for(j=0;j<=Matriz2.Num_columnas;j++){
                        for(k=0;k<=Matriz1.Num_columnas;k++){
                   
                   
                            dato1=Integer.parseInt(modelo1.getValueAt(i, k).toString());
                            dato2=Integer.parseInt(modelo2.getValueAt(k, j).toString());
                            s=s+dato1*dato2;
                        } 
                    modelo3.setValueAt(s+"", i,j);
                    s=0;
                    }
                }
            }
        
        
        
    }//GEN-LAST:event_btnmultiActionPerformed

    private void f1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f1ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void f2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_f2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_f2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c2ActionPerformed

    private void btngMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngMouseClicked
        // TODO add your handling code here:
                
        DefaultTableModel modelo1 = (DefaultTableModel) Matrizz.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) Matrizz1.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) Matrizf.getModel();
        
        Matriz1.Num_filas =Integer.parseInt(f1.getText());
        Matriz1.Num_columnas =Integer.parseInt(c1.getText());
        Matriz2.Num_filas =Integer.parseInt(f2.getText());
        Matriz2.Num_columnas =Integer.parseInt(c2.getText());
        
        
            
            if(Matriz1.Num_filas<10 && Matriz1.Num_filas<10 && Matriz2.Num_filas<10 && Matriz2.Num_filas<10){
            
                modelo1.setRowCount(Matriz1.Num_filas);
                modelo1.setColumnCount(Matriz1.Num_columnas);
                modelo2.setRowCount(Matriz2.Num_filas);
                modelo2.setColumnCount(Matriz2.Num_columnas);
            
            }
            else
            {
                lberror.setText("la dimension de la matriz se excede");
            }
        
        
        
    }//GEN-LAST:event_btngMouseClicked

    private void btnsumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsumaActionPerformed

    private void btntrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btntrasActionPerformed

    private void btnsumaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnsumaMouseClicked
        // TODO add your handling code here:
        int dato1,dato2,k,i,j,s=0;
        
        DefaultTableModel modelo1 = (DefaultTableModel) Matrizz.getModel();
        DefaultTableModel modelo2 = (DefaultTableModel) Matrizz1.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) Matrizf.getModel();
               
        if(Matriz1.Num_filas==Matriz2.Num_filas && Matriz1.Num_columnas==Matriz2.Num_columnas){
            
        
            modelo1.setRowCount(Matriz1.Num_filas);
            modelo1.setColumnCount(Matriz1.Num_columnas);
            modelo2.setRowCount(Matriz2.Num_filas);
            modelo2.setColumnCount(Matriz2.Num_columnas);
            
            modelo3.setRowCount(Matriz1.Num_filas);
            modelo3.setColumnCount(Matriz1.Num_columnas);
            
            for(i=0;i<Matriz1.Num_filas;i++){
                for(j=0;j<Matriz2.Num_columnas;j++){
               
                   dato1=Integer.parseInt(modelo1.getValueAt(i, j).toString());
                   dato2=Integer.parseInt(modelo2.getValueAt(i, j).toString());
                   s=dato1+dato2;
                
               modelo3.setValueAt(s+"", i,j);
               s=0;
                }
        }
        }
        else{
            lberror.setText("la suma no se puede efectuar");
        }   
            
        
        
    }//GEN-LAST:event_btnsumaMouseClicked

    private void btntrasMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrasMouseMoved
        // TODO add your handling code here:
        lberror.setText("solo para la matriz A");
    }//GEN-LAST:event_btntrasMouseMoved

    private void btntrasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btntrasMouseClicked
        // TODO add your handling code here:
        int dato1,i,j;
        
        DefaultTableModel modelo1 = (DefaultTableModel) Matrizz.getModel();
        DefaultTableModel modelo3 = (DefaultTableModel) Matrizf.getModel();
        
            modelo3.setRowCount(Matriz1.Num_columnas);
            modelo3.setColumnCount(Matriz1.Num_filas);   
            
            for(i=0;i<Matriz1.Num_filas;i++){
                for(j=0;j<Matriz1.Num_columnas;j++){
               
                   dato1=Integer.parseInt(modelo1.getValueAt(i,j).toString());
                   
                   
                
               modelo3.setValueAt(dato1+"", j,i);
               
                }
        }
            
            
    }//GEN-LAST:event_btntrasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Matrizf;
    private javax.swing.JTable Matrizz;
    private javax.swing.JTable Matrizz1;
    private javax.swing.JButton btng;
    private javax.swing.JButton btnmulti;
    private javax.swing.JButton btnsuma;
    private javax.swing.JButton btntras;
    private javax.swing.JTextField c1;
    private javax.swing.JTextField c2;
    private javax.swing.JTextField f1;
    private javax.swing.JTextField f2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lberror;
    // End of variables declaration//GEN-END:variables
}
